### ISSUE TITLE
Can timezone be specified for mode = timestamp?

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-jdbc#103] opened 2016-07-27 16:44 UTC
My DB system clock is on BST (UTC +1). If I use `mode = timestamp` and insert data to a table (Oracle) as : 

```
SQL> create table kafka_test (ts1 timestamp not null,foo int);

Table created.

SQL> insert into kafka_test select sysdate-1,42 from dual;

1 row created.

SQL> commit;

Commit complete.

SQL> select * from kafka_test;

TS1                             FOO
-------------------------       ----------
27-JUL-16 05.39.45.000000 PM    42
```

Kafka Connect won't pick up that row until an hour from now, as it is using UTC in its timestamp, even though it returns the `CURRENT_TIMESTAMP` from the Oracle box. 

```
[2016-07-27 17:39:01,923] DEBUG Executing prepared statement with timestamp value = 1469554131000 (2016-07-26 17:28:51.000)  end time 2016-07-27 16:39:01.923 (io.confluent.connect.jdbc.TimestampIncrementingTableQuerier:171)
```

Is there a way to specify to kafka-connect-jdbc which timezone it should be using? 

thanks.

(connector config for reference: )

```
name=oracle-soe-incr-source
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=10


connection.url=jdbc:oracle:thin:soe/soe@db12-01.moffatt.me:1521/pdb
topic.prefix=ora-soe-
mode=timestamp
timestamp.column.name=TS1
table.whitelist=KAFKA_TEST
```

**Comment by shikhar** [comment] 2016-10-27 21:57
@rmoff does it work to specify a function to convert to UTC as the `timestamp.column.name`?

seems like for Oracle this is `sys_extract_utc`

**Comment by jorgheymans** [comment] 2017-05-19 11:41
confirming that sys_extract_utc works on Oracle, ran into this problem as well. 

I think it's worth mentioning in the documentation that the timestamp mode works with UTC timestamps.

**Comment by Sarvesh-D** [comment] 2017-07-31 06:24
@jorgheymans hi, i too am not able to use timestamp mode properly with oracle DB. can you tell me what you changed in the connector config that made it work for you. it would be great if you can paste the working connector config here. Thanks.

**Comment by jorgheymans** [comment] 2017-07-31 07:27
in the DDL we defined the timestamp like below:

```
EVENT_TIMESTAMP TIMESTAMP(6) default SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) not null,
```

**Comment by rrangine** [comment] 2017-08-24 19:49
@Sarvesh-D @rmoff Hi, I am stuck with the same issue. Any ideas how to solve around this as I can not change my source Oracle Timezone. For instance, the source records have timestamp : 24-AUG-17 03.37.23.149104000 PM -04:00(by the time I am posting this comment) .

**Comment by rrangine** [comment] 2017-08-28 14:28
@mancini77 Thanks. I have refactored the source code to use alternative signature of executeQuery() in TimestampIncrementingTableQuerier.java to not use UTC . So, the client uses the local timezone and is aligning.

**Comment by nielswind** [comment] 2017-08-29 09:29
Hi - I have the same exact problem - in CET (UTC+2). 
@rrangine Looking forward to test when available.
Any known work-around for 3.3.x  without using `sys_extract_utc` (not possible in my case) ?

**Comment by rrangine** [comment] 2017-09-04 23:27
@nielswind I have changed the source code on local repo and so I have not created a PR. All local tests are succeeded for the code changes in TimestampIncrementingTableQuerier.java. Look for the alternative signature for stmt.setTimestamp(). Let me know if you need more help. Thanks.

**Comment by chinnusujitha** [comment] 2018-08-10 11:14
I'm facing the same problem, i tried to get the data from PostgreSQL by using connector, when my ddl schema is in UTC for timestamp connector is working fine, but when my timestamp field is my local time connector is not working. Due to some reasons i cannot change my timestamp field to UTC. So please help me on how to handle it.

**Comment by julienmmm** [comment] 2018-08-27 13:44
I am facing the same issue with an Oracle DB and a timestamp field.
According to the log bellow:
[2018-08-27 15:26:30,511] DEBUG executing query select CURRENT_TIMESTAMP from dual to get current time from database (io.confluent.connect.jdbc.dialect.OracleDatabaseDialect:462)
[2018-08-27 15:26:30,512] DEBUG Executing prepared statement with start time value = 2018-08-27 13:07:09.901 end time = 2018-08-27 13:26:53.900 and incrementing value = 227 (io.confluent.connect.jdbc.source.TimestampIncrementingCriteria:138)

It seems that the jdbc connector with Oracle dialects returns a UTC timestamp which it uses to compare local time (My test was made at 15:26 and the current timestmap set in the connector was 13:26).

I've tries to change the ORacle session time zone with environment variables (export ORA_SDTZ='Europe/Brussels') but it seems to make no difference.

any idea how t change that?

**Comment by julienmmm** [comment] 2018-09-29 13:06
Here is the workaround we have found which does not require any modification of the table structure.
For a table tab whose timestamp column is updated_date  we use the query bellow in our connector config:
`with tab_utc  as (select t.*, sys_extract_utc(cast(t.updated_date as timestamp)) as updated_date_utc from tab t) select * from tab_utc `
And set the property timestamp.column.name to updated_date_utc in your connector config file.

**Comment by nik09541** [comment] 2018-11-01 07:12
Hi All
I am still facing issue with the mode timestamp in jdbc kafka source connector. All of the above recommendations have been implemented by me. I have converted the timestamp column to UTC format even using

alter table TEMP add UPDATED_DATE TIMESTAMP(6) default SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) not null;

Following is the connector config

name=TRANSACTION
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=10
connection.url=jdbc:oracle:thin:@service:1701:CONNECTOR
connection.user=TRANSACTION
connection.password=txn#789
mode=timestamp
timestamp.column.name=UPDATED_DATE
validate.non.null=false
#incrementing.column.name=ID
#query=select * from temp inner join tempdata on temp.id=tempdata.id
topic.prefix=test
batch.max.rows=3
timestamp.delay.interval.ms=3000
table.whitelist=TEMP
table.poll.interval.ms=3000

Issues being faced

Kafka connector not polling data and not pushing to topic when I use timestamp mode or timestamp+incrementing mode , however only incrementing mode works fine.
2.I am not able to use multiple tables to poll out data from them by mentioning them in table.whitelist separated by comma like this
table.whitelist=TEMP,TEMPDATA
connector always picks up second table and creates a topic with prefix 'test'
and fullname testTEMPDATA. In case i mention auto.create.topics.enable=true , then nothing happens in logs and no error.

Please help over these issues as I might be missing on something. Urgent help is required .

Thanks in Advance!

**Comment by nik09541** [comment] 2018-11-01 07:12
![db](https://user-images.githubusercontent.com/44663724/47837903-8a092e80-dda5-11e8-9040-87a1d8f42570.JPG)
My db:

**Comment by wicknicks** [comment] 2018-11-09 19:07
The timezone can now be specified using the `db.timezone` property. Marking this as resolved.

**Closed by wicknicks** 2018-11-09 19:07 UTC
Labels: enhancement

**Comment by nik09541** [comment] 2018-11-12 09:43
Not working still with  this property also

**Comment by mariusneo** [comment] 2018-11-12 12:30
@nik09541 the property has been recently added to the `master` branch (and it will be generally available only from 5.2.x version of the kafka-connect-jdbc). so in case you want to make use of it you need to build master locally.
Note that in order to build it locally, you'll need to build the following projects:
- common  
- kafka 
- kafka-connect-jdbc

**Comment by ussama-rafique** [comment] 2018-11-20 10:57
This issue should be resolved by using "timestamp.delay.interval.ms" property (set a negative value for this property).
If your timezone is UTC+1, then 1 hour = 3600 s = 3600000 ms, add the following to your connector:
"timestamp.delay.interval.ms": "-3600000"
problem solved!!

**Comment by mariusneo** [comment] 2018-11-20 11:01
@ussama-rafique indeed this solution would work until next winter/summer time shift. So if @nik09541 is ok with changing a few times a year his connnector's configuration this is indeed the way to go.

**Comment by ussama-rafique** [comment] 2018-11-20 11:06
@mariusneo yes...you are right. The user will have to update it twice a year if their time change in summer/winter. For me at least, this is the perfect solution as our time don't change.

**Comment by nik09541** [comment] 2018-11-21 04:31
Thanks guys for help. Timestamp mode is working now.
Another issue being faced was regarding using multiple tables in table.whitelist (mentioned in second point above).   Serious issue being faced is below: 
I have tried to configure Kafka JDBC connect in order to have streams from an existing table. The existing table unfortunately have a id field that has purging from another event(i.e the rows are not strictly incrementing). As of now we have created script to move the records to another custom table we created with a custom id and timestamp field. But this is not working.During the first insert into custom table with data from existing table there is no event seen on kafka topic. But on updating the timestamp column the event is noticed on connectror. I did try the bulk option, but then the processing goes in an endless loop while trying to read it from avro consumer (but the bulk table option is not going to take-off either as the audit tables are going to be huge).

insert into reference (select * from customer where customer_ref_id in (5004145,5004146,5004161,5004162,5004178));
Above insert registers no event in kafka connector as id id not strictly incrementing in customer table.

insert into reference (customer_ref_id ,updated_date) values (id_seq.nextval,current_timestamp);
This insert works as it is inserting data with a sequence into table. Event is noticed on kafka connector

I have tried the query mode also it also doesnt work.

Please help if we can poll out the existing data on kafka topic for a non incrementing exisiting id of a table which is having purging .

**Comment by rmoff** [comment] 2018-11-22 10:47
@nik09541 please start a new issue, since these questions aren't related to the original issue. You might want to also try the #connect channel on http://cnfl.io/slack

**Comment by nik09541** [comment] 2018-11-26 05:45
Kafka Connector not able to create topic if auto creation is turned off #534  .raised

**Comment by rmoff** [comment] 2018-11-29 11:04
@wicknicks which release of Confluent Platform will this new config option (`db.timezone`) be available in? Will it be there in 5.1? thanks.

**Comment by mariusneo** [comment] 2018-11-29 12:37
Currently in 5.2

I can do a PR for 5.1 branch if you guys from Confluent agree.

**Comment by nik09541** [comment] 2018-11-30 04:15
Hi guys 
when 5.2 version for kafka connector  will be available? As it is needed urgently for handling numeric columns.

**Comment by sajhak** [comment] 2019-09-02 06:11
I'm using confluent 5.3.x, and have set the connector config to my timezone
`"db.timezone": "JST"`
Is the way i configure is correct? I still can't get data read into Oracle. 
connect logs shows the end time in UTC 
` DEBUG Executing prepared statement with timestamp value = 1970-01-01 00:00:00.000 end time = 2019-09-02 06:10:24.214 (io.confluent.connect.jdbc.source.TimestampIncrementingCriteria)
`
06.10 time is UTC

**Comment by helpermethod** [comment] 2019-12-10 13:43
Same problem here.

**Comment by brandonwittwer** [comment] 2020-01-16 20:55
@sajhak Are either your database or kafka instance boxes living in UTC?  I've had the reverse issue, where my applied db.timezone didn't affect the right-hand boundary at all, but what got written to SQL was an EASTERN (GMT-5) time... always... regardless of the setting.

**Comment by Psykepro** [comment] 2021-04-07 15:59
I've got a similar issue just that I got loaded initial/current data and after that got no events for inserts or updates. The Timezone on the server is BST so I specified "db.timezone": "Europe\London" as BST wasn't valid Timezone Id and still got no success.

**Comment by mariusneo** [comment] 2021-04-07 16:29
Try maybe "Europe/London" instead.

**Comment by Psykepro** [comment] 2021-04-07 16:47
Actually, the value I've used is `"Europe/London"` my bad I mistook it here not there. Still don't update :S

**Comment by mariusneo** [comment] 2021-04-07 20:08
I've just had a look in the source code

https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java#L826

and also tried on my machine

```
System.out.println(TimeZone.getTimeZone(ZoneId.of("Europe/London")));
```

The `db.timezone` setting should work with `Europe/London`
Probably it is another issue in your `SELECT` statement. Are the source entries coming too late ?

**Comment by Psykepro** [comment] 2021-04-08 08:18
The problem is that it is loading only initial data / current data and after that no other record is processed neither insert or the update. The version of kafka connect is 6.0.2 and you can see the config I'm using here: https://github.com/confluentinc/kafka-connect-jdbc/issues/1033
