### ISSUE TITLE
Bytes handled incorrectly in JDBC Sink for Postgres

### ISSUE THREAD

**Issue by slepkin** [confluentinc/kafka-connect-jdbc#404] opened 2018-05-03 20:14 UTC
In [PostgreSqlDialect.java](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/sink/dialect/PostgreSqlDialect.java), the Schema.Type `BYTES` is mapped to `BLOB`, which [does not exist in Postgres](https://www.postgresql.org/docs/10/static/datatype-binary.html). Instead, it should be mapped to `BYTEA`.

**Comment by rhauch** [comment] 2018-05-04 13:58
See also #333 which I hope to merge soon.

**Comment by rhauch** [comment] 2018-05-04 14:05
@slepkin I think #333 doesn't fix it, either. I added a comment to that PR.

**Comment by slepkin** [comment] 2018-05-04 17:42
Thanks, @rhauch. Do you have a rough notion of when you'll add this fix to #333 and merge to master? If you suspect it'll take more than a month, I might try to tackle it.

**Comment by rhauch** [comment] 2018-05-04 20:53
No, I'm hoping to merge in the next few weeks.

**Comment by paulbandler** [comment] 2018-11-22 10:51
Did this issue ever get resolved and released?  I'm experiencing it in version kafka-connect-jdbc: 5.0.1
[2018-11-22 10:48:51,202] ERROR WorkerSinkTask{id=jdbc-sink-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:577)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: type "blob" does not exist
  Position: 246

        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:94)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: type "blob" does not exist

**Comment by slepkin** [comment] 2018-11-23 06:42
Instead of using the Confluent JDBC Sink, we got around this issue by writing our own Consumer/Producer using the [python wrapper](https://docs.confluent.io/current/clients/confluent-kafka-python/) of librdkafka.

**Comment by rhauch** [comment] 2018-11-26 17:02
See #271 (not mergeable). Will address shortly.

**Comment by rhauch** [comment] 2018-11-26 17:11
BTW, another workaround is to create the tables manually before running the connector.

**Comment by rhauch** [comment] 2018-11-26 23:47
Fixed with #535

**Closed by rhauch** 2018-11-26 23:47 UTC
