### ISSUE TITLE
Looks like we are not handling some SQLExceptions correctly

### ISSUE THREAD

**Issue by gwenshap** [confluentinc/kafka-connect-jdbc#38] opened 2016-01-30 00:30 UTC
I observed a case where disconnect from MySQL caused us to poll() in a tight loop, returning null every time. We should probably figure out unrecoverable SQL errors and either reconnect ourselves or kill the task so another worker can take over.

```
[2016-01-29 23:46:30,118] ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='bar', query='null', topicPrefix='test-', timestampColumn='null', incrementingColumn='id'}: com.mysql.jdbc.exceptions.jdbc4.MySQLQueryInterruptedException: Query execution was interrupted (io.confluent.connect.jdbc.JdbcSourceTask)
[2016-01-29 23:46:30,122] ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='bar', query='null', topicPrefix='test-', timestampColumn='null', incrementingColumn='id'}: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 9 milliseconds ago.  The last packet sent successfully to the server was 3 milliseconds ago. (io.confluent.connect.jdbc.JdbcSourceTask)
[2016-01-29 23:46:30,122] ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='bar', query='null', topicPrefix='test-', timestampColumn='null', incrementingColumn='id'}: java.sql.SQLException: No operations allowed after statement closed. (io.confluent.connect.jdbc.JdbcSourceTask)
[2016-01-29 23:46:30,122] ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='bar', query='null', topicPrefix='test-', timestampColumn='null', incrementingColumn='id'}: java.sql.SQLException: No operations allowed after statement closed. (io.confluent.connect.jdbc.JdbcSourceTask)
[2016-01-29 23:46:30,122] ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='bar', query='null', topicPrefix='test-', timestampColumn='null', incrementingColumn='id'}: java.sql.SQLException: No operations allowed after statement closed. (io.confluent.connect.jdbc.JdbcSourceTask)
```

The last error repeats in tight loop forever.

**Comment by BenjaminDavison** [comment] 2016-02-27 23:00
Hi Gwen,

Also seeing this for many errors in MSSQL also.

Ben

**Comment by muftring** [comment] 2016-03-07 14:23
I believe that I'm seeing the same problem with an IBM DB2 connection. The logged error and exception raised is:

`11[2016-03-07 07:48:13,730] ERROR Error while trying to get updated table list, ignoring and waiting for next table poll interval (io.confluent.connect.jdbc.TableMonitorThread:107)
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.19.49] A communication error occurred during operations on the connection's underlying socket, socket input stream, 
or socket output stream.  Error location: Reply.fill() - insufficient data (-1).  Message: Insufficient data. ERRORCODE=-4499, SQLSTATE=08001
```

**Comment by muftring** [comment] 2016-04-20 17:27
What is the status of this issue? Is there a plan to include a fix in an upcoming milestone?

**Comment by gitUserX2** [comment] 2016-05-13 09:27
+1 This issue caused disk space problems on our side so we needed to come up with workarounds to handle the log spamming. The frequency is so high that we ended up with 100GB of logs ...

**Comment by swapna-s** [comment] 2016-05-13 22:11
I think I see this if the incrementing column is not "id". 
incrementing.column.name=id

**Comment by ryanpersaud** [comment] 2016-05-31 17:35
+1 Also seeing this error message, and general SQL Server 'sluggishness.'  Is it possible that the retries can degrade the performance of the SQL Server that Kafka Connect is configured to monitor?

**Comment by willyhoang** [comment] 2016-10-11 19:34
I also see the same kind of behavior using Postgres. I set up a Postgres db and source connector. When I tear down the Postgres db the "Failed to run query" log loops because the connection has been closed. Maybe the task should be killed and marked as failed?

**Comment by shikhar** [comment] 2016-10-11 23:17
Er I guess I didn't quite get to this 'soon'. Digging around now to reproduce and debug.

**Comment by shikhar** [comment] 2016-10-12 23:46
I would appreciate if someone could try out https://github.com/confluentinc/kafka-connect-jdbc/pull/144

**Closed** 2016-10-14 03:21 UTC
