### ISSUE TITLE
kafka connect Oracle JDBC sink connector not working 

### ISSUE THREAD

**Issue by dgvj-work** [confluentinc/kafka-connect-jdbc#266] opened 2017-08-23 02:31 UTC
I have data in a kafka topic in JSON form and I want to insert the data into Oracle table  but I am having schema related error 

Error 1
**org.apache.kafka.connect.errors.DataException: JsonDeserializer with schemas.enable requires "schema" and "payload" fields and may not contain additional fields**

Error 2- 
Converting byte[] to Kafka Connect data failed due to serialization error

**JSON Data in Kafka Topic -**
{"Item":"600019","Sourcing Reason":"CORRECT_NODE","Postal Code":"M8X1H9","OrderNum":"2236779306","Intended Node Distance":8.24,"Chosen Node":"2090","Quantity":1,"Order Date":15025,"Intended Node":"2090","Chosen Node Distance":8.24,"Sourcing Logic":"proximity"}

**sink-connector.properties**
name=oracle_sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=DGVJ
connection.url=jdbc:oracle:thin:@hostname:portnumber:sid
connection.user=user_id
connection.password=password
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false               // tried giving both true and false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false         // // tried giving both true and false
auto.create=true
auto.evolve=true

Please suggest - 

--

**Comment by rmoff** [comment] 2017-08-30 09:32
Duplicate of [StackOverflow post](https://stackoverflow.com/questions/45928768/kafka-connect-jdbc-sink-connector-not-working), answered there.

**Closed by rmoff** 2017-08-30 09:32 UTC
