### ISSUE TITLE
i can not set multiple incremental column names

### ISSUE THREAD

**Issue by JerryAlbinA** [confluentinc/kafka-connect-jdbc#190] opened 2017-02-04 16:15 UTC
Hi All, 
When Kafka-Connect connecting to Postgresql,we found that 'incrementing.column.name' property (etc/kafka-connect-jdbc/quickstart-postgres.properties)  accepting only one column, but in my case, I have many incremental columns from different tables.

how to set multiple column names into  'incrementing.column.name' property  ?

my 'etc/kafka-connect-jdbc/quickstart-postgres.properties'  file:
name=test-postgresql-jdbc-autoincrement
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:postgresql://127.0.0.1/demo?user=sample&password=sample123
mode=incrementing
incrementing.column.name=id
topic.prefix=sample-postgresql-jdbc-

Quick responses are more appreciated !!.. Thank you.

**Comment by bruce-szalwinski** [comment] 2017-03-20 18:52
https://github.com/confluentinc/kafka-connect-jdbc/issues/113 suggests creating database views for each table to be sourced.  In the view, you can map each different primary key to the same name in the view.

    create or replace view1(id, ...) as select table1_primary_key, ...;
    create or replace view2(id, ...) as select table2_primary_key, ...;

**Comment by wicknicks** [comment] 2018-11-09 22:31
Marking this as a duplicate of #36.

**Closed by wicknicks** 2018-11-09 22:31 UTC
Labels: duplicate, enhancement
