### ISSUE TITLE
Unknown configuration 'batch.max.rows' Error when publishing messages to topic connected to jdbc sink

### ISSUE THREAD

**Issue by yousufdev** [confluentinc/kafka-connect-jdbc#777] opened 2020-01-22 09:59 UTC
I have a JDBC sink connector running with the following config
`{
    "name": "postgres-sink-1",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "connection.url": "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=docker",
        "topics": "db",
        "auto.create": "true",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter.schemas.enable": "true"
    }
}`

But When I publish json messages (schema included) I get this Error. The connector was working for me before with the same configuration but all a sudden this error occurred. Following is my message which I am publishing to the topic

`{
  "schema": {
    "type": "struct",
    "fields": [
      {
        "type": "int64",
        "optional": false,
        "field": "id"
      },
      {
        "type": "string",
        "optional": true,
        "field": "name"
      },
      {
        "type": "string",
        "optional": true,
        "field": "email"
      },
      {
        "type": "string",
        "optional": true,
        "field": "department"
      }
    ],
    "optional": false,
    "name": "sample"
  },
  "payload": {
    "id": 1,
    "name": "jhon",
    "email": "john@gmail.com",
    "department": "support"
  }
}`

**Comment by cricket007** [comment] 2020-01-22 22:03
Can you share the logs? That message will indeed come up from AdminClient configs or Producer/Consumer Config, but it is not an error

**Comment by isole** [comment] 2020-01-24 10:41
Happens here as well. Here's my stack-trace:


`[2020-01-24 11:37:27,733] DEBUG INSERT sql: INSERT INTO `connect_test`(`payload`) VALUES(?) deleteSql: null meta: FieldsMetadata{keyFieldNames=[], nonKeyFieldNames=[payload], allFields={payload=SinkRecordField{schema=Schema{STRING}, name='payload', isPrimaryKey=false}}} (io.confluent.connect.jdbc.sink.BufferedRecords:128)
[2020-01-24 11:37:27,733] DEBUG Closing BufferedRecords with updatePreparedStatement: null deletePreparedStatement: null (io.confluent.connect.jdbc.sink.BufferedRecords:250)
[2020-01-24 11:37:27,736] ERROR WorkerSinkTask{id=jdbc-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
	at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:159)
	at org.apache.kafka.common.config.AbstractConfig.getInt(AbstractConfig.java:173)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.initializePreparedStatement(GenericDatabaseDialect.java:341)
	at io.confluent.connect.jdbc.dialect.MySqlDatabaseDialect.initializePreparedStatement(MySqlDatabaseDialect.java:79)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.createPreparedStatement(GenericDatabaseDialect.java:322)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:136)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-01-24 11:37:27,740] DEBUG WorkerSinkTask{id=jdbc-sink-0} Skipping offset commit, no change since last commit (org.apache.kafka.connect.runtime.WorkerSinkTask:427)
[2020-01-24 11:37:27,740] DEBUG WorkerSinkTask{id=jdbc-sink-0} Finished offset commit successfully in 0 ms for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:264)
[2020-01-24 11:37:27,740] ERROR WorkerSinkTask{id=jdbc-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
	at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:159)
	at org.apache.kafka.common.config.AbstractConfig.getInt(AbstractConfig.java:173)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.initializePreparedStatement(GenericDatabaseDialect.java:341)
	at io.confluent.connect.jdbc.dialect.MySqlDatabaseDialect.initializePreparedStatement(MySqlDatabaseDialect.java:79)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.createPreparedStatement(GenericDatabaseDialect.java:322)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:136)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	... 10 more
`

**Comment by cricket007** [comment] 2020-01-24 13:15
Please mention what version you're running. It's there in the source code...

https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java#L85

**Comment by yousufdev** [comment] 2020-01-24 13:49
@cricket007 When i used the master branch version this error pops up and the message also doesn't get to the DB, but now I switched to the version 5.4.0 provided on confluent hub and its working fine.

**Comment by cricket007** [comment] 2020-01-24 13:56
I would suggest always using a release branch because those are what you'd get as part of downloading the whole platform. Master branch is designated as the development branch

**Comment by gharris1727** [comment] 2020-02-03 20:26
This was fixed in #784 .

**Closed by gharris1727** 2020-02-03 20:26 UTC
