### ISSUE TITLE
Missing Updates with Timestamp+incrementing mode in Postgres

### ISSUE THREAD

**Issue by salemn** [confluentinc/kafka-connect-jdbc#172] opened 2016-12-01 20:58 UTC
Hello Everybody,

i'm deploying kafka-connect, in timestamp+incrementing mode, on our platform in order to get data transferred from our main database to secondary one. I'm using source and sink connectors. Both databases are Postgres databases

I'm facing a missing lines issues. the case is not frequent but happens from time to time.

Here is the situation:

```
postgres=# CREATE TABLE foo(id serial primary key, updated timestamp without time zone);
CREATE TABLE
postgres=# CREATE TRIGGER update_updated_column
postgres-#   BEFORE INSERT OR UPDATE
postgres-#   ON foo
postgres-#   FOR EACH ROW
postgres-#   EXECUTE PROCEDURE update_updated_column();
--
SESSION 1:
postgres=# begin;
BEGIN
postgres=# INSERT INTO foo(updated) VALUES (null);
INSERT 0 1
postgres=# SELECT * FROM foo;
 id |          updated           
----+----------------------------
  1 | 2016-12-01 08:53:54.099995
(1 ligne)
---

SESSION 2 :
postgres=# BEGIN;
BEGIN
postgres=# INSERT INTO foo(updated) VALUES (null);
INSERT 0 1
postgres=# SELECT * FROM foo;
 id |          updated           
----+----------------------------
  3 | 2016-12-01 08:54:46.420757
(1 ligne)

postgres=# COMMIT;
COMMIT
postgres=# SELECT * FROM foo;
 id |          updated           
----+----------------------------
  3 | 2016-12-01 08:54:46.420757
(1 ligne)
----

SESSION 1 :
postgres=# COMMIT;
COMMIT
postgres=# SELECT * FROM foo;
 id |          updated           
----+----------------------------
  1 | 2016-12-01 08:53:54.099995
  3 | 2016-12-01 08:54:46.420757
(2 lignes)
```

Line 1 is missing in my target database.

Is there any way to use to source connector to avoird such situation?

Best Regards
Naoufel

**Comment by shikhar** [comment] 2016-12-08 19:31
@salemn is the missing row present in the Kafka topic written to by the source connector? (to isolate whether the issue is on the source or the sink side of things)

**Comment by salemn** [comment] 2016-12-09 10:57
@shikhar i think that the issue is in the source connector as The row is missing in the topic.

**Comment by gilbsgilbs** [comment] 2016-12-11 01:48
@gfodor I think the issue is a basic race conditon.

1. Transaction TR0 begins, inserts row R0 (at updated = T0), and hangs without committing.
2. Transaction TR1 begins, inserts row R1 (at updated = T1 > T0), and commits.
3. Source connector polls. It sees R2, but not R1 (because it's not committed yet). Last updated date is now at T1. Source connector will assume that nothing could have happened before T1.
4. T0 commits eventually.
5. Source connector polls, but misses R0 because T0 < T1.

**Comment by ewencp** [comment] 2017-01-04 00:59
@salemn Did you set timestamp.delay.interval.ms? Without a delay there is a possibility that transactions may still be open and not visible to queriers despite timestamps & rows that are "newer" are visible. You'd want to set this value to be conservatively longer than the longest time you expect a transaction to take. This is just a fundamental limitation of working through the JDBC interface.

**Comment by willyhoang** [comment] 2017-01-20 06:12
If I'm using a source connector with incrementing mode (with only an incrementing id and no timestamp), is there an equivalent config that we could use to resolve this race condition?

**Comment by SemanticBeeng** [comment] 2017-03-23 07:10
Can this https://github.com/confluentinc/kafka-connect-jdbc/issues/172#issuecomment-266255088 be happening when using a "mode": "timestamp+incrementing" and "timestamp.delay.interval.ms": 3000 (assumption is that transactions end faster than 1 sec? @ewencp

**Comment by gilbsgilbs** [comment] 2017-04-21 19:40
@SemanticBeeng Assuming that the delay is always higher than the slowest transaction, that is perfectly fine. However, a tiny delay such as 3 seconds will be difficult to keep in the long run. One day or another, you'll have some misses and need to implement a backup mechanism or increase the delay. I don't know what is your use-case, but I would say that most of the time, if it's really important for you to not miss anything, you'll need to increase the delay drastically, trading off the lag. That's the main reason why we gave up on using kafka-connect-jdbc.

**Comment by song860918** [comment] 2017-05-16 20:41
@willyhoang Did you get the incrementing mode problem figured out? We are running into the same issue.

**Comment by makearl** [comment] 2017-05-30 19:32
For incrementing mode, it looks like this becomes a problem once the connector finishes backfilling and catches up to realtime. Should there be a similar configuration item to "timestamp.delay.interval.ms" for incrementing mode?

**Comment by dizzy0ny** [comment] 2018-02-16 00:19
@gilbsgilbs what are you using instead of kafka-connect-jdbc and why wouldn't any other odbc driver exhibit the same problem?

**Comment by bibhatripathi** [comment] 2018-03-14 04:32
Hi, did the original author of this issue get the issue resolved? I am facing the same issue with SQL Server. Basically, it seems like even in "timestamp+incrementing" mode, the connect is doing a strictly "incrementing". No updates involving earlier incrementing IDs show up but new rows inserted with higher IDs do show up.

**Comment by bibhatripathi** [comment] 2018-03-14 04:35
Hi, did the original author of this issue get the issue resolved? I am facing the same issue with SQL Server. Basically, it seems like even in "timestamp+incrementing" mode, the connect is doing a strictly "incrementing". No updates involving earlier incrementing IDs show up but new rows inserted with higher IDs do show up.

**Comment by bibhatripathi** [comment] 2018-03-14 04:38
Hi, did the original author of this issue get the issue resolved? I am facing the same issue with SQL Server. Basically, it seems like even in "timestamp+incrementing" mode, the connect is doing a strictly "incrementing". No updates involving earlier incrementing IDs show up but new rows inserted with higher IDs do show up. @salemn

**Comment by vibtrip** [comment] 2018-03-14 12:03
@ewencp was timestamp+incrementing in the original issue here resolved with the delay?? Is 5 seconds deays good enough for polling every second?

**Comment by gilbsgilbs** [comment] 2018-03-14 12:54
@dizzy0ny We ended up using nothing and dropped the project. Any ODBC driver will suffer from the same issues because it tries to solve a problem with wrong tools. There's a reason for DBMS replication systems being based on transaction ids: it's the only way to guarantee consistency and real-time. Not using XIDs (one way or the other) implies a trade-off between consistency (missed rows due to "transactions shadowing" for instance) and real-time (requires a huge lag to ensure all transactions are over). This might be OK in some (maybe most) cases, but I really reckon the doc should be more honest about this. Anyhow, some tools that let you leverage logical replication to solve the same problem have emerged recently. Take a look at [Debezium](http://debezium.io/) or [Bottledwater](https://github.com/confluentinc/bottledwater-pg) (which seems abandoned) or even [AWS DMS](https://aws.amazon.com/dms/). They might be a better fit.

@vibtrip I don't think your problem is related to the OP's. The issue is about some marginal missed updates. Please open another issue.

**Comment by dizzy0ny** [comment] 2018-03-15 23:01
@gilbsgilbs the only way i can think of to solve this may be to violate ACID and use read uncommitted.  that presents a whole lot of other issues however.  
However, increasing the timestamp.delay.interval.ms doesn't necessarily mean you are incurring lag does it?  i think it simply mean the query will look back further..meaning it may return more data than it should which may have been processed already.  That's what i thought and could be wrong.

**Comment by gilbsgilbs** [comment] 2018-03-15 23:23
@dizzy0ny 

> the only way i can think of to solve this may be to violate ACID and use read uncommitted. that presents a whole lot of other issues however.

Yeah we also thought of this, but as you mention it has other terrible drawbacks. You'll indeed see the rows soon enough, however if they're rollbacked, you will replicate them which you most likely really want to avoid. 

> However, increasing the timestamp.delay.interval.ms doesn't necessarily mean you are incurring lag does it? i think it simply mean the query will look back further..meaning it may return more data than it should which may have been processed already. That's what i thought and could be wrong.

I may also be wrong and have misinterpreted the doc. But,

> The first execution will fetch all available records (i.e. starting at timestamp 0) until current time minus the delay. Every following execution will get data from the last time we fetched until current time minus the delay.

Which means to me that you'll lag behind the delay. As I understand it, the connector will always continue where it last finished. This is probably to avoid spamming the database and fetching too many records, or even worst, pushing tons of duplicate events into Kafka. I think this is totally fine, expected and correct behavior.

**Comment by vibtrip** [comment] 2018-03-15 23:37
@dizzy0ny @gilbsgilbs
My problem appears to be resolved with increased offset.flush.interval.ms for common workers config, and timestamp.delay.interval.ms . We were facing marginally missed updates from subsequent database  transactions. The first set of inserts always worked fine, but in subsequent batches if there were some updates to existing rows plus new inserts, we were seeing the updates gettig dropped, which by the Kafka sorts the records were always the first few due to incremental IDs.

**Comment by SemanticBeeng** [comment] 2018-03-16 06:35
Indeed `Debezium` has (change data capture is) the proper paradigm.

**Comment by tushtinaryani** [comment] 2018-04-06 18:44
I have looked at numerous possibilities of why we might miss some records. Can anyone please advice if this issue can happen in NOLOCK SQL queries too? Or I can eliminate issue mentioned in this thread if we are using NOLOCK.

Please advise at the earliest, thanks!

**Comment by AnilGodaba** [comment] 2018-05-08 12:15
@salemn was your issue resolved? we are facing similar issue (records are not picked from view sometimes). Please share your resolution if your issue was fixed with changing timestamp.delay.interval.ms and or offset.flush.interval.ms. 
Can any other in this forum help?

**Comment by wicknicks** [comment] 2018-11-09 21:33
@AnilGodaba @tushtinaryani: missing records typically happen when records are inserted/updated out of order. A workaround for that is to add a new column which contains a monotonically increasing timestamp or incrementing id for the JDBC connector to detect changes, or specify a `query` that can determine the changes in the table. Or as other people have suggested in this thread, consider using Debezium for CDC capture.

**Comment by ekoutanov** [comment] 2019-06-06 06:34
This question has also been asked on [stackoverflow](https://stackoverflow.com/questions/49973970/confluent-connect-jdbc-and-exactly-once-delivery/56471579#56471579) post. It is somewhat concerning that the Confluent documentation fails to mention this as a potential safety consideration, in spite of this being a well-known issue, open for 2.5 years.

**Comment by rmoff** [comment] 2021-04-21 09:52
If you need to guarantee that you will capture every single event from your database, you need to use _log-based_ Change Data Capture (with connectors such as Debezium). 

The JDBC Source connector implements _query-based_ Change Data Capture.

For detailed explanation of this see 

* Video: https://youtu.be/8rv-8UQ7BfI?t=717
* Slides: https://talks.rmoff.net/bf5tqR/no-more-silos-integrating-databases-and-apache-kafka#sJ3P9Q5

**Closed by rmoff** 2021-04-21 09:52 UTC
Labels: question

**Comment by peknu** [comment] 2023-06-09 07:25
It would be possible to solve this problem for a connector using mode incrementing if the increment size (normally just 1 for sequences) is known and a config parameter for look behind is added to the connector. The connector can then keep track of missed ids for the incrementing column for a configurable period and add them to the where clause.

`${query} WHERE ${incrementing.column.name} > ${last seen id} OR ${incrementing.column.name} in ${list of potentially missed ids}`

For example, say that the `poll.interval.ms` is 1000 and it is possible to configure a new `poll.lookbehind.ms` that is set to 2000.
If the connector last seen id is 24 and the next poll finds 26, it would add the `OR ID in (25)` clause in the following two polls.
