### ISSUE TITLE
Closed connection errors that go away with a restart

### ISSUE THREAD

**Issue by trungduyvu** [confluentinc/kafka-connect-jdbc#139] opened 2016-10-04 03:35 UTC
I keep running into closed connection error running kafka-connect-jdbc talking to sql server

> ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='null', query='SELECT * FROM dbo.vw_SnapApi_Products2', topicPrefix='datamart-products-new', timestampColumn='SnapProductsModifiedDate', incrementingColumn='ProductID'}: com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed. (io.confluent.connect.jdbc.JdbcSourceTask:239)

The error would go away after I restart the connect-distributed process. It looks like kafka-connect-jdbc is using old connection and keep failing. I think it should catch this exception and reopen the connection if possible

Here is the config of the connector

> [2016-10-04 03:29:44,116] INFO JdbcSourceTaskConfig values:
>         timestamp.column.name = SnapProductsModifiedDate
>         incrementing.column.name = ProductID
>         validate.non.null = true
>         query = SELECT * FROM dbo.vw_SnapApi_Products2
>         batch.max.rows = 100
>         timestamp.delay.interval.ms = 0
>         table.blacklist = []
>         table.poll.interval.ms = 60000
>         table.whitelist = []
>         mode = timestamp+incrementing
>         topic.prefix = datamart-products-new
>         tables = []
>         poll.interval.ms = 30000
>         connection.url = jdbc:sqlserver://xxx
>  (io.confluent.connect.jdbc.JdbcSourceTaskConfig:178)

**Comment by jallen1788** [comment] 2016-10-05 16:17
👍 having this issue too

**Comment by shikhar** [comment] 2016-10-11 23:17
Closing as dupe of #38

**Closed by shikhar** 2016-10-11 23:17 UTC

**Comment by dmahajan1609** [comment] 2017-08-21 19:26
Having the same exact issue with JDBCSourceConnector for MS SQL Server 2014. Could someone please point me to a solution if there's one? Thank you in advance!
