### ISSUE TITLE
Oracle source connector: timestamp.column.name is case sensitive

### ISSUE THREAD

**Issue by akhilanandbv003** [confluentinc/kafka-connect-jdbc#369] opened 2018-02-21 05:05 UTC
The timestamp column name seems to be case sensitive and gives some weird error:
java.sql.SQLSyntaxErrorException: ORA-00904: “row_modify_date”: invalid identifier
 ERROR Failed to run query for table TimestampIncrementingTableQuerier{name='null', query='select * from table', topicPrefix='topicname', timestampColumn='ROW_MODIFY_DATE', incrementingColumn='null'}: {} (io.confluent.connect.jdbc.source.JdbcSourceTask:221)

java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

But it works as soon as I change it to ROW_MODIFY_DATE

**Comment by milanogc** [comment] 2018-06-22 19:30
The problem is that the connector puts quotes around the column name and that makes Oracle case sensitive.

**Comment by rhauch** [comment] 2019-02-08 15:41
It is possible to bypass these quotes with #572, which was recently made and has not yet been released, though it will be in the 5.0.2, 5.1.1, and 5.2.0 releases whenever they occur. In the meantime, you can build the connector locally and try the new feature to disable quoting.

I'll mark this as closed, but feel free to reopen if you try the feature and it does not work for you.

**Closed** 2020-04-23 22:42 UTC
