### ISSUE TITLE
Please support Postgres jsonb

### ISSUE THREAD

**Issue by understructure** [confluentinc/kafka-connect-jdbc#46] opened 2016-02-23 16:32 UTC
Getting this warning for a table with a JSONB column:

`WARN JDBC type 1111 not currently supported`

I haven't tried regular JSON.

+1 for supporting Postgres boolean type:

```
WARN Ignoring record due to SQL error: (io.confluent.connect.jdbc.JdbcSourceTask:73)
org.postgresql.util.PSQLException: Bad value for type byte : f
```

Thanks in advance!

**Comment by vikasdp** [comment] 2016-05-12 01:58
+1

**Comment by ryananguiano** [comment] 2016-05-18 07:47
Same issue

**Comment by robconrad** [comment] 2016-07-16 15:16
+1

**Comment by Oktaz** [comment] 2016-08-18 14:41
+1

**Comment by dandanmylady** [comment] 2017-08-25 02:43
+1

**Comment by khgitting** [comment] 2017-11-29 19:41
I'd also like to see this. Is this another issue that will be easier with https://github.com/confluentinc/kafka-connect-jdbc/issues/303 ?

**Comment by venergiac** [comment] 2017-12-13 12:42
+1

**Comment by Deninc** [comment] 2018-03-22 11:58
+1

**Comment by minh5** [comment] 2018-04-05 16:40
Running into this as well, +1

**Comment by rhauch** [comment] 2018-04-05 16:57
Thanks for the suggestion, and all the +1s. The naive approach to solving this is to treat `json` and `jsonb` as a string, which would essentially encode the JSON into a single string field. This would work across all converters (not just JSON). Is this sufficient? I've already incorporated this into the [RDBMS-specific dialects|https://github.com/confluentinc/kafka-connect-jdbc/pull/333/files#diff-9a03fcf4950ba15217add89d2a4664a9R113] in #333 (for issue #303), at least on the source connector side.

OTOH, extracting the JSON content into a Connect `Struct` or `Map` is also possible, but likely has other implications and complications with respect to schemas. Here, any variation in JSON structure would cause schema changes that could make things messy, unless we have a "smart schema inference" mechanism that would compute a schema that covers all JSON structures seen so far. But this also has lots of risk and complications.

**Comment by austinnichols101** [comment] 2018-04-05 19:12
It would be sufficient for my current use-cases.

**Comment by akashdeep01** [comment] 2019-08-12 07:53
+1

**Comment by matthewrj** [comment] 2019-10-09 23:16
Currently when using `JdbcSinkConnector`, it attempts to write `jsonb` data as `VARCHAR`.
Connect config:
```
{
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "table.name.format": "messages",
    "tasks.max": "1",
    "topics": "topic1",
    "transforms": "HoistPayload",
    "transforms.HoistPayload.field": "message_json",
    "auto.evolve": "false",
    "name": "postgres-sink",
    "auto.create": "false",
    "connection.url": "jdbc:postgresql://postgres:5432/postgres?user=postgres&password=example",
    "value.converter": "org.apache.kafka.connect.storage.StringConverter",
    "insert.mode": "upsert",
    "transforms.HoistPayload.type": "org.apache.kafka.connect.transforms.HoistField$Value",
    "pk.mode": "kafka",
    "pk.fields": "topic,partition,offset"
}
```
Table:
```
CREATE TABLE messages (
    "topic" VARCHAR(64) NOT NULL,
    "partition" INTEGER NOT NULL,
    "offset" BIGINT NOT NULL,
    "message_json" jsonb,
    PRIMARY KEY("topic", "partition", "offset")
);
```
Error:
```
INSERT INTO "messages" ("topic","partition","offset","message_json") VALUES ('topic1',0,0,'{"foo": "bar"}') ON CONFLICT ("topic","partition","offset") DO UPDATE SET "message_json"=EXCLUDED."message_json" was aborted: ERROR: column "message_json" is of type jsonb but expression is of type character varying
Hint: You will need to rewrite or cast the expression.
```

Is it possible for the `PostgreSqlDatabaseDialect` to use `?::JSON` in `buildUpsertQueryStatement` for column types `jsonb`?
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java#L240

**Comment by gopalakrishnan-subramani** [comment] 2019-12-03 05:04
This has been long pending issue, really a show stopped at many projects. Surprised Kafka team doesn't care about it.  Since Kafka-connect-jdbc lies within Confluent license, it is not ready enterprise module.

**Comment by rhyek** [comment] 2020-03-01 04:22
Working on a new project where I am considering having Kafka as my single-source-of-truth, where a SQL database and Firestore would both behave as parallel Kafka Connect sinks. With Firestore, Kafka, and Avro schemas all handling nested Json documents well, what alternatives are there for PostgreSQL and this JDBC sink plugin not working well with JSONB columns?

**Comment by OneCricketeer** [comment] 2020-05-05 14:10
> what alternatives are there for PostgreSQL

Try a noSQL database? 

Neo4J is great for such types of nested collections.

**Comment by Dishwasha** [comment] 2020-05-08 05:30
This works instead
```
CREATE OR REPLACE FUNCTION varchar_to_jsonb (varchar) RETURNS jsonb AS $$ SELECT to_jsonb($1) $$ LANGUAGE SQL;
CREATE OR REPLACE CAST (varchar as jsonb) WITH FUNCTION varchar_to_jsonb(varchar) AS IMPLICIT;
```

**Comment by kabureu** [comment] 2020-05-19 15:07
> varchar_to_jsonb

How can use this PG function with Kafka connector during sink time?

**Comment by Dishwasha** [comment] 2020-05-19 15:09
@kabureu It's automatic within postgres on insert/upsert.

**Comment by kabureu** [comment] 2020-05-19 15:12
> @kabureu It's automatic within postgres on insert/upsert. Just add this on the PG side on your database/schema.

Cool, also do we specify field(s) that we want this to apply to? as I only need to cast subset of columns

**Comment by Dishwasha** [comment] 2020-05-19 15:18
@kabureu This would cast all fields with a source type of varchar (internally this is what the kafka connector uses even for text) that is going to a destination column of type jsonb.  If you somehow limited those fields, you would get an error due to no ability to cast.  Not sure why you would want that.

**Comment by sergyv** [comment] 2020-06-09 07:41
@Dishwasha I have noticed that it escapes double quotes, so I have changed your function a bit to remove escaping as follows:
`CREATE OR REPLACE FUNCTION varchar_to_jsonb (varchar) RETURNS jsonb AS $$ SELECT regexp_replace(trim(both '"' from $1), '\\"', '"', 'g')::jsonb $$ LANGUAGE SQL;`

**Comment by KyleMccr** [comment] 2020-07-22 15:16
For awareness the CREATE CAST solution does not work in Amazon RDS.  It requires full admin owner which belongs to Amazon while your admin account is slightly restricted.

**Comment by sourgoyal** [comment] 2020-08-04 16:09
Target type json/jsonb is not supported in `io.confluent.connect.jdbc.JdbcSinkConnector`. 
Solution is using `varchar_to_jsonb` but it will be applied to all varchar columns. How can we specify the column name in this case?
Also it doesn't work in AWS RDS? then what are the alternatives?

**Comment by alstel** [comment] 2020-10-15 15:42
Would still love to see this data type supported.

**Comment by robdesbois** [comment] 2020-11-19 17:42
This appears to be fixed in the current connector. The Postgresql dialect for `JdbcSinkConnector` will now automatically convert to UUID, JSON and JSONB column types [[source](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java#L76)].

I then configured the connector as below. I've omitted irrelevant parts, so it's incomplete as-is. It uses the `ToJSON` transform from jcustenborder's [common transforms](https://github.com/jcustenborder/kafka-connect-transform-common/) plugin, to convert the message value to JSON, then hoists it into a `data` field in a struct so it maps onto a column in the table also called `data`.

Note that auto table-creation won't create JSONB columns for you (see [`PostgreSqlDatabaseDialect.getSqlType()`](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java#L219)), so you'll have to manually create your table.

```json
{
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "transforms": "valueToJSON,wrapValue",
    "transforms.valueToJSON.type": "com.github.jcustenborder.kafka.connect.transform.common.ToJSON$Value",
    "transforms.valueToJSON.schemas.enable": "false",

    "transforms.wrapValue.type":"org.apache.kafka.connect.transforms.HoistField$Value",
    "transforms.wrapValue.field":"data"
}
```

**Comment by typik89** [comment] 2021-11-07 09:56
Please close the issue because jsonb is supported now

**Comment by NathanNam** [comment] 2022-05-23 22:47
Hello,

Sorry for the delayed response. https://github.com/confluentinc/kafka-connect-jdbc/pull/875 has addressed the JSONB and JSON support for PostgreSQL.

The following software versions have been used.
- Confluent Platform v7.0.1
- JDBC Connector v10.4.1
- Amazon RDS for PostgreSQL

# JSONB
Create a table (the following example has been taken from [Faster Operations with the JSONB Data Type in PostgreSQL](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/) )

```
CREATE TABLE books (  
  book_id serial NOT NULL,
  data jsonb
);
```

![image](https://user-images.githubusercontent.com/8757699/169916160-dca12bf3-bb59-4ecb-b032-63fd4cfe0f2d.png)

Insert a few records

```
INSERT INTO books VALUES (1, '{"title": "Sleeping Beauties", "genres": ["Fiction", "Thriller", "Horror"], "published": false}');  
INSERT INTO books VALUES (2, '{"title": "Influence", "genres": ["Marketing & Sales", "Self-Help ", "Psychology"], "published": true}');  
INSERT INTO books VALUES (3, '{"title": "The Dictator''s Handbook", "genres": ["Law", "Politics"], "authors": ["Bruce Bueno de Mesquita", "Alastair Smith"], "published": true}');  
INSERT INTO books VALUES (4, '{"title": "Deep Work", "genres": ["Productivity", "Reference"], "published": true}');  
INSERT INTO books VALUES (5, '{"title": "Siddhartha", "genres": ["Fiction", "Spirituality"], "published": true}');  
Commit;
```

![image](https://user-images.githubusercontent.com/8757699/169916210-1f7c72aa-0323-4cd7-831a-25b761dfa72c.png)

Create a JDBC Source connector with the following config.
```
{
  "name": "jdbc_source_postgres_demo_jsonb",
  "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "connection.url": "jdbc:postgresql://<database-url>:5432/confluent",
          "connection.user": "<username>",
          "connection.password": "<password>",
          "tasks.max": "1",
          "topic.prefix":"postgres-",
          "mode":"incrementing",
          "incrementing.column.name":"book_id",
          "poll.interval.ms":"1000",
          "key.converter": "io.confluent.connect.avro.AvroConverter",
          "key.converter.schema.registry.url": "http://localhost:8081",
          "value.converter": "io.confluent.connect.avro.AvroConverter",
          "value.converter.schema.registry.url": "http://localhost:8081"
      }
}
```

The following avro schema is created by JDBC Source
```
{
  "connect.name": "books",
  "fields": [
    {
      "name": "book_id",
      "type": "int"
    },
    {
      "default": null,
      "name": "data",
      "type": [
        "null",
        "string"
      ]
    }
  ],
  "name": "books",
  "type": "record"
}
```

The following avro records have been captured by JDBC Source.
```
(base) ➜  bin kafka-avro-console-consumer -bootstrap-server localhost:9092 --property schema.registry.url=http://localhost:8081 --topic postgres-books --from-beginning
{"book_id":1,"data":{"string":"{\"title\": \"Sleeping Beauties\", \"genres\": [\"Fiction\", \"Thriller\", \"Horror\"], \"published\": false}"}}
{"book_id":2,"data":{"string":"{\"title\": \"Influence\", \"genres\": [\"Marketing & Sales\", \"Self-Help \", \"Psychology\"], \"published\": true}"}}
{"book_id":3,"data":{"string":"{\"title\": \"The Dictator's Handbook\", \"genres\": [\"Law\", \"Politics\"], \"authors\": [\"Bruce Bueno de Mesquita\", \"Alastair Smith\"], \"published\": true}"}}
{"book_id":4,"data":{"string":"{\"title\": \"Deep Work\", \"genres\": [\"Productivity\", \"Reference\"], \"published\": true}"}}
{"book_id":5,"data":{"string":"{\"title\": \"Siddhartha\", \"genres\": [\"Fiction\", \"Spirituality\"], \"published\": true}"}}
^CProcessed a total of 5 messages
```

Create another table (the following example has been taken from [Faster Operations with the JSONB Data Type in PostgreSQL](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/) )
```
CREATE TABLE postgresbooks (  
  book_id serial NOT NULL,
  data jsonb
);
```

Create a JDBC Sink connector with the following config.

```
{
    "name": "jdbc_sink_postgres_demo_jsonb",
    "config": {
            "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
            "connection.url": "jdbc:postgresql://<database-url>:5432/confluent",
            "connection.user": "<username>",
            "connection.password": "<password>",
            "tasks.max": "2",
            "topics": "postgres-books",
            "auto.create": "false",
            "auto.evolve": "true",
            "dialect.name": "PostgreSqlDatabaseDialect",
            "insert.mode": "insert",
            "table.name.format":"postgresbooks",
            "batch.size": 1,
            "key.converter": "io.confluent.connect.avro.AvroConverter",
            "key.converter.schema.registry.url": "http://localhost:8081",
            "value.converter": "io.confluent.connect.avro.AvroConverter",
            "value.converter.schema.registry.url": "http://localhost:8081"
            
        }
  }
```

![image](https://user-images.githubusercontent.com/8757699/169916373-c3860b6f-3ba8-4061-8452-615ef4f1018b.png)


# JSON
Create a table (the following example has been taken from [Faster Operations with the JSONB Data Type in PostgreSQL](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/) )
```
CREATE TABLE booksjson (  
  book_id serial NOT NULL,
  data json
);
```
![image](https://user-images.githubusercontent.com/8757699/169916487-b7cdf644-fc02-418a-9a09-a598a1204c0a.png)

Insert a few records

```
INSERT INTO books VALUES (1, '{"title": "Sleeping Beauties", "genres": ["Fiction", "Thriller", "Horror"], "published": false}');  
INSERT INTO books VALUES (2, '{"title": "Influence", "genres": ["Marketing & Sales", "Self-Help ", "Psychology"], "published": true}');  
INSERT INTO books VALUES (3, '{"title": "The Dictator''s Handbook", "genres": ["Law", "Politics"], "authors": ["Bruce Bueno de Mesquita", "Alastair Smith"], "published": true}');  
INSERT INTO books VALUES (4, '{"title": "Deep Work", "genres": ["Productivity", "Reference"], "published": true}');  
INSERT INTO books VALUES (5, '{"title": "Siddhartha", "genres": ["Fiction", "Spirituality"], "published": true}');  
Commit;
```

![image](https://user-images.githubusercontent.com/8757699/169916511-6ac32c34-322b-4a0b-ab5f-71f3281756ed.png)

Create a JDBC Source connector with the following config.

```
{
  "name": "jdbc_source_postgres_demo_json",
  "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "connection.url": "jdbc:postgresql://<database-url>:5432/confluent",
          "connection.user": "<username>",
          "connection.password": "<password>",
          "tasks.max": "1",
          "topic.prefix":"postgres-",
          "mode":"incrementing",
          "incrementing.column.name":"book_id",
          "poll.interval.ms":"1000",
          "key.converter": "io.confluent.connect.avro.AvroConverter",
          "key.converter.schema.registry.url": "http://localhost:8081",
          "value.converter": "io.confluent.connect.avro.AvroConverter",
          "value.converter.schema.registry.url": "http://localhost:8081"
      }
}
```

The following avro schema is created by JDBC Source.
```
{
  "connect.name": "booksjson",
  "fields": [
    {
      "name": "book_id",
      "type": "int"
    },
    {
      "default": null,
      "name": "data",
      "type": [
        "null",
        "string"
      ]
    }
  ],
  "name": "booksjson",
  "type": "record"
}
```

The following avro records have been captured by JDBC Source.
```
(base) ➜  bin kafka-avro-console-consumer -bootstrap-server localhost:9092 --property schema.registry.url=http://localhost:8081 --topic postgres-booksjson --from-beginning
{"book_id":1,"data":{"string":"{\"title\": \"Sleeping Beauties\", \"genres\": [\"Fiction\", \"Thriller\", \"Horror\"], \"published\": false}"}}
{"book_id":2,"data":{"string":"{\"title\": \"Influence\", \"genres\": [\"Marketing & Sales\", \"Self-Help \", \"Psychology\"], \"published\": true}"}}
{"book_id":3,"data":{"string":"{\"title\": \"The Dictator's Handbook\", \"genres\": [\"Law\", \"Politics\"], \"authors\": [\"Bruce Bueno de Mesquita\", \"Alastair Smith\"], \"published\": true}"}}
{"book_id":4,"data":{"string":"{\"title\": \"Deep Work\", \"genres\": [\"Productivity\", \"Reference\"], \"published\": true}"}}
{"book_id":5,"data":{"string":"{\"title\": \"Siddhartha\", \"genres\": [\"Fiction\", \"Spirituality\"], \"published\": true}"}}
^CProcessed a total of 5 messages
```

Create another table (the following example has been taken from [Faster Operations with the JSONB Data Type in PostgreSQL](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/) )
```
CREATE TABLE postgresbooksjson (  
  book_id serial NOT NULL,
  data json
);
```

Create a JDBC Sink connector with the following config.
{
    "name": "jdbc_sink_postgres_demo_jsonb",
    "config": {
            "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
            "connection.url": "jdbc:postgresql://<database-url>:5432/confluent",
            "connection.user": "<username>",
            "connection.password": "<password>",
            "tasks.max": "2",
            "topics": "postgres-books",
            "auto.create": "false",
            "auto.evolve": "true",
            "dialect.name": "PostgreSqlDatabaseDialect",
            "insert.mode": "insert",
            "table.name.format":"postgresbooksjson",
            "batch.size": 1,
            "key.converter": "io.confluent.connect.avro.AvroConverter",
            "key.converter.schema.registry.url": "http://localhost:8081",
            "value.converter": "io.confluent.connect.avro.AvroConverter",
            "value.converter.schema.registry.url": "http://localhost:8081"
            
        }
  }

![image](https://user-images.githubusercontent.com/8757699/169916746-4f77bb2c-7077-4e50-b7d0-97a7be84a418.png)

**Closed by NathanNam** 2022-05-23 22:47 UTC
Labels: enhancement

**Comment by OneCricketeer** [comment] 2022-05-27 16:20
> following avro schema is created by [...]

IIUC, this requires some schema of a type string to match the jsonb column? In other words, it's not possible to insert a Connect Struct type into a jsonb column? For example, Debezium Mongo Connector could create nested Avro record types from its documents.

**Comment by OneCricketeer** [comment] 2022-05-31 16:44
@NathanNam Yes, I understand the example, but that didn't answer my question if Struct Connect types can be directly inserted into a json column, or will there need to be some transform to stringify it?

**Comment by NathanNam** [comment] 2022-05-31 22:31
@OneCricketeer Would the following schema and records meet what you are looking for?
Avro Schema
```
{
  "connect.name": "ksql.users",
  "fields": [
    {
      "name": "registertime",
      "type": "long"
    },
    {
      "name": "userid",
      "type": "string"
    },
    {
      "name": "regionid",
      "type": "string"
    },
    {
      "name": "gender",
      "type": "string"
    },
    {
      "name": "interests",
      "type": {
        "items": "string",
        "type": "array"
      }
    },
    {
      "name": "contactinfo",
      "type": {
        "type": "map",
        "values": "string"
      }
    }
  ],
  "name": "users",
  "namespace": "ksql",
  "type": "record"
}
```

Kafka records
```
(base) ➜  bin kafka-avro-console-consumer --bootstrap-server localhost:9092 --from-beginning --topic users --property schema.registry.url=http://localhost:8081
{"registertime":1514393301632,"userid":"User_7","regionid":"Region_4","gender":"MALE","interests":["Game","News"],"contactinfo":{"zipcode":"92617","state":"CA","phone":"9492229999","city":"Irvine"}}
{"registertime":1518932494199,"userid":"User_5","regionid":"Region_3","gender":"OTHER","interests":["News","Travel"],"contactinfo":{"zipcode":"92617","state":"CA","phone":"9492229999","city":"Irvine"}}
```
If not, could you share some examples?

**Comment by OneCricketeer** [comment] 2022-06-01 05:15
@NathanNam Seems like a fine example; it's not a string and the JDBC Sink would therefore try to generate a table with 6 columns, as I understand.

**Comment by NathanNam** [comment] 2022-06-02 23:37
The following records are created by Datagen Source (``"quickstart": "users_"``)

Avro Schema
```
{
  "connect.name": "ksql.users",
  "fields": [
    {
      "name": "registertime",
      "type": "long"
    },
    {
      "name": "userid",
      "type": "string"
    },
    {
      "name": "regionid",
      "type": "string"
    },
    {
      "name": "gender",
      "type": "string"
    },
    {
      "name": "interests",
      "type": {
        "items": "string",
        "type": "array"
      }
    },
    {
      "name": "contactinfo",
      "type": {
        "type": "map",
        "values": "string"
      }
    }
  ],
  "name": "users",
  "namespace": "ksql",
  "type": "record"
}
```

Kafka records
```
(base) ➜  bin kafka-avro-console-consumer --bootstrap-server localhost:9092 --from-beginning --topic users --property schema.registry.url=http://localhost:8081
{"registertime":1514393301632,"userid":"User_7","regionid":"Region_4","gender":"MALE","interests":["Game","News"],"contactinfo":{"zipcode":"92617","state":"CA","phone":"9492229999","city":"Irvine"}}
{"registertime":1518932494199,"userid":"User_5","regionid":"Region_3","gender":"OTHER","interests":["News","Travel"],"contactinfo":{"zipcode":"92617","state":"CA","phone":"9492229999","city":"Irvine"}}
```

If a JDBC Sink is created with the following config,
```
"auto.create": "true",
"auto.evolve": "true",
```
the connector will fail with the following error message.
```
Caused by: org.apache.kafka.connect.errors.ConnectException: null (MAP) type doesn't have a mapping to the SQL database column type


If you create a table similar to the following one,
```
CREATE TABLE users (  
  registertime bigint,
  userid text,
  regionid text,
  gender text,
  interests text [],
  contactinfo jsonb);

```
the connector will fail with the following error message.
```
Caused by: org.apache.kafka.connect.errors.ConnectException: Unsupported source data type: MAP
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.bindField(GenericDatabaseDialect.java:1654)
```

At this moment, string could be mapped to ``JSON`` or ``JSONB`` but map or array is not support in JDBC Sink yet.

```

**Comment by OneCricketeer** [comment] 2022-06-03 00:05
I more was asking about putting all / subset of fields directly into a json column. As I suspected, data needs manipulated to be stringified first. 

> map or array is not support in JDBC Sink yet.

Primitive arrays are supported (#1044). I already knew maps weren't.

**Comment by mastoj** [comment] 2022-12-19 08:42
Is this the same connector as the hosted postgres one? I really struggle to get that working beyond the basic stuff.

**Comment by OneCricketeer** [comment] 2022-12-19 12:25
@mastoj It might be. Please don't chain on new issues to this thread.

Create a new one, or use Confluent Forum / Slack / Stackoverflow for help. Be sure to include any configs and errors you're having.

**Comment by malik-ashter** [comment] 2023-02-07 18:21
@NathanNam I tried to create the sink connector as you specified in the [comment](https://github.com/confluentinc/kafka-connect-jdbc/issues/46#issuecomment-1135209669). i registered the schema and added the records as in the comment. but the output is not json instead it is in single quotes so the insert into db fails. following is the piece of logs.
`INSERT INTO "postgresbooks"("book_id","data") VALUES(1,'{"title": "Sleeping Beauties", "genres": ["Fiction", "Thriller", "Horror"], "published": false}') was aborted: ERROR: column "data" is of type jsonb but expression is of type character varying`
